"""Streamlit app: Gen-AI Career Path Finder."""

import streamlit as st

from career_data import CAREER_STATEMENTS
from llm_client import generate_career_report
from scoring import calculate_scores


def _validate_responses(responses):
    """Return a list of statement IDs that are missing responses."""
    missing_ids = []
    for statement in CAREER_STATEMENTS:
        if responses.get(statement["id"]) is None:
            missing_ids.append(statement["id"])
    return missing_ids


def _build_responses_from_ui():
    """Read user selections from session state and return deterministic mapping."""
    responses = {}
    for statement in CAREER_STATEMENTS:
        statement_id = statement["id"]
        responses[statement_id] = st.session_state.get(statement_id)
    return responses


def main():
    st.set_page_config(page_title="Gen-AI Career Path Finder", page_icon="🧭", layout="centered")

    st.title("Gen-AI Career Path Finder")
    st.caption("This app combines deterministic scoring with LLM-generated career guidance.")

    st.markdown("### Rate each statement")
    st.write("Use: **-1 = Disagree**, **0 = Neutral**, **1 = Agree**.")

    # Deterministic input collection
    for statement in CAREER_STATEMENTS:
        st.radio(
            label=statement["text"],
            options=[-1, 0, 1],
            key=statement["id"],
            horizontal=True,
            index=None,  # force explicit user choice for validation demo
        )

    if st.button("Generate My Career Report", type="primary"):
        responses = _build_responses_from_ui()
        missing_ids = _validate_responses(responses)

        if missing_ids:
            st.error(
                "Please answer all 10 statements before generating your report."
                f" Missing: {', '.join(missing_ids)}"
            )
            st.stop()

        try:
            score_summary = calculate_scores(responses)
        except ValueError as exc:
            st.error(f"Validation error: {exc}")
            st.stop()
        except Exception as exc:
            st.error(f"Unexpected scoring error: {exc}")
            st.stop()

        # Clear separation: deterministic section
        st.markdown("---")
        st.subheader("Deterministic Result")
        st.write("The output below is produced entirely by regular Python logic.")

        score_rows = []
        for category, score in score_summary["category_scores"].items():
            score_rows.append({"Category": category, "Score": score})

        st.table(score_rows)
        st.write(f"**Top categories:** {', '.join(score_summary['top_categories'])}")
        st.write(f"**Total score:** {score_summary['total_score']}")

        # Clear separation: LLM section
        st.markdown("---")
        st.subheader("LLM-Generated Report")
        st.write("The output below is generated by the language model from your score summary.")

        with st.spinner("Generating your personalized career report..."):
            report_markdown = generate_career_report(score_summary)
        st.markdown(report_markdown)


if __name__ == "__main__":
    main()
